Products = {
    ["normal"] = {
        { name = "tosti", price = 2, amount = 50, },
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "kurkakola", price = 2, amount = 50, },
        { name = "twerks_candy", price = 2, amount = 50, },
        { name = "snikkel_candy", price = 2, amount = 50, },
        { name = "sandwich", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 15, amount = 50, },
        { name = "bandage", price = 100, amount = 50, },
        { name = "lighter", price = 2, amount = 50, },
        { name = "rolling_paper", price = 2, amount = 5000,  },
    },
    ["bar"] = {
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 15, amount = 50, },
    },
    ["hardware"] = {
        { name = "lockpick", price = 200, amount = 50, },
        { name = "weapon_wrench", price = 250, amount = 250, },
        { name = "weapon_hammer", price = 250, amount = 250, },
        { name = "weapon_bat", price = 500, amount = 50,  requiredGang = { "lostmc" } },  -- Gang only options in stores
        { name = "screwdriverset", price = 350, amount = 50, },
        { name = "phone", price = 850, amount = 50, },
        { name = "radio", price = 250, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "firework1", price = 50, amount = 50, },
        { name = "firework2", price = 50, amount = 50, },
        { name = "firework3", price = 50, amount = 50, },
        { name = "firework4", price = 50, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
        { name = "cleaningkit", price = 150, amount = 150, },
        { name = "advancedrepairkit", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 } },
    },
    ["weedshop"] = {
        { name = "joint", price = 10, amount = 1000, },
        { name = "weapon_poolcue", price = 100, amount = 1000, },
        { name = "weed_nutrition", price = 20, amount = 1000, },
        { name = "empty_weed_bag", price = 2, amount = 1000, },
        { name = "rolling_paper", price = 2, amount = 1000, },
    },
    ["burgershot"] = {
        { name = "bleeder", price = 250, amount = 1000, },
        { name = "heartstopper", price = 200, amount = 1000, },
        { name = "softdrink", price = 200, amount = 1000, },

    },
    ["gearshop"] = {
        { name = "diving_gear", price = 2500, amount = 10, },
        { name = "jerry_can", price = 200, amount = 50, },
    },
    ["leisureshop"] = {
        { name = "parachute", price = 2500, amount = 10, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "diving_gear", price = 2500, amount = 10, },
    },
    ["weapons"] = {
        { name = "weapon_knife", price = 250, amount = 250, },
        { name = "weapon_bat", price = 250, amount = 250, },
        { name = "weapon_hatchet",price = 250, amount = 250,  requiredJob = { ["mechanic"] = 0, ["bcso"] = 0 } },
        { name = "weapon_pistol", price = 2500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_snspistol", price = 1500, amount = 5, requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
        { name = "weapon_vintagepistol", price = 4000, amount = 5, requiresLicense = {"weapon", "hunting"}, requiresItem = {"weaponlicense", "huntinglicense"} },
        { name = "pistol_ammo", price = 250, amount = 250,  requiresLicense = {"weapon"}, requiresItem = {"weaponlicense"} },
    },
    ["coffeeplace"] = {
        { name = "coffee", price = 5, amount = 500 },
        { name = "lighter", price = 2, amount = 50 },
    },
    ["casino"] = {
        { name = 'casinochips', price = 1, amount = 999999 },
        { name = 'wheeltoken', price = 5000, amount = 999999 },
    },
    ["electronics"] = {
        { name = "phone", price = 850, amount = 50 },
        { name = "radio", price = 250, amount = 50, },
        { name = "fitbit", price = 400, amount = 150, },
    },
    ["vending"] = {
        { name = "water_bottle", price = 100, amount = 25, },
        { name = "kurkakola", price = 100, amount = 25, },
        { name = "sprunk", price = 100, amount = 25, },
        { name = "sprunklight", price = 100, amount = 25, },
        { name = "ecola", price = 100, amount = 25, },
        { name = "ecolalight", price = 100, amount = 25, },
        { name = "twerks_candy", price = 100, amount = 25, },
        { name = "snikkel_candy", price = 100, amount = 25, },
    },
    ["blackmarket"] = {
        { name = "radioscanner", price = 850, amount = 5 },
    },
    ["mechanic"] = {
        { name = "mechanic_tools", price = 1000, amount = 10,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "toolbox", price = 750, amount = 10,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "ducttape", price = 100, amount = 100,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "paintcan", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "tint_supplies", price = 500, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "underglow_controller", price = 10000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "cleaningkit", price = 100, amount = 100,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "turbo", price = 25000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "engine1", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "engine2", price = 4000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "engine3", price = 6000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "engine4", price = 12000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "transmission1", price = 6000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "transmission2", price = 8000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "transmission3", price = 20000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "brakes1", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "brakes2", price = 2000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "brakes3", price = 3000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "car_armor", price = 25000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "suspension1", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "suspension2", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "suspension3", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "suspension4", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "bprooftires", price = 50000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "drifttires", price =250, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "nos", price = 250000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "hood", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "roof", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "spoiler", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "bumper", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "skirts", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "exhaust", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "seat", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "livery", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "tires", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "horn", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "internals", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "externals", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "customplate", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "headlights", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "rims", price = 1000, amount = 100,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "rollcage", price = 1000, amount = 50,  requiredJob = { ["mechanic"] = 0 }  },
        { name = "noscolour", price = 1000, amount = 50,   requiredJob = { ["mechanic"] = 0 } },
        { name = "repairkit", price = 100, amount = 50,  requiredJob = { ["mechanic"] = 0 } },

    },
    ["police"] = {
        { name = "weapon_combatpistol", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "weapon_pistol_mk2", price = 1, amount = 100,  requiredJob = { ["bcso"] = 2 }  },
        { name = "weapon_stungun", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "weapon_pumpshotgun", price = 1, amount = 50,   requiredJob = { ["bcso"] = 4 } },
        { name = "weapon_carbinerifle", price = 1, amount = 50,  requiredJob = { ["bcso"] = 5 } },
        { name = "pistol_ammo", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "shotgun_ammo", price = 1, amount = 100,  requiredJob = { ["bcso"] = 4 }  },
        { name = "rifle_ammo", price = 1, amount = 50,  requiredJob = { ["bcso"] = 5 }  },
        { name = "handcuffs", price = 1, amount = 50,   requiredJob = { ["bcso"] = 0 } },
        { name = "cuffkeys", price = 1, amount = 50,  requiredJob = { ["bcso"] = 50 } },
        { name = "weapon_flashlight", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "empty_evidence_bag", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "ifaks", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 }  },
        { name = "firstaid", price = 1, amount = 50,   requiredJob = { ["bcso"] = 0 } },
        { name = "radio", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 } },
        { name = "heavyarmor", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 } },
        { name = "leo-gps", price = 1, amount = 50,  requiredJob = { ["bcso"] = 0 } },
    }

}