INSERT INTO `items` (`name`, `label`, `weight`) VALUES
  ('redw', 'Redwood Pack', 1),
  ('marlboro', 'Marlboro Pack', 1),
  ('cubancigar', 'Cuban Cigar', 1),
  ('davidoffcigar', 'Davidoff Cigar', 1),
  ('redwcig', 'Rredwood Cigarette', 1),
  ('marlborocig', 'Marlboro Cigarette', 1),
  ('vape', 'Vape', 1),
  ('bongo', 'Bong', 1),
  ('og_kush_joint', 'Og Kush Joint', 1),
  ('blue_dream_joint', 'Blue Dream Joint', 1),
  ('purple_haze_joint', 'Purple Haze Joint', 1),
  ('banana_kush_joint', 'Banana Lush Joint', 1),
  ('og_kush_weed', 'Og Kush Weed 1G', 1),
  ('blue_dream_weed', 'Blue Dream Weed 1G', 1),
  ('banana_kush_weed', 'Banana Kush Weed 1G', 1),
  ('purple_haze_weed', 'Purple Haze Weed 1G', 1),
  ('banana_kush_bag', 'Banana Kush Bag', 1),
  ('blue_dream_bag', 'Blue Dream Bag', 1),
  ('liquid', 'Liquid', 1),
  ('ocb_paper', 'Ocb Paper', 1),
  ('og_kush_bag', 'Og Kush Bag', 1),
  ('purple_haze_bag', 'Purple Haze Bag', 1),

;